# Generated by Django 3.0.4 on 2020-03-29 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('fio', models.CharField(blank=True, max_length=45, null=True)),
                ('rank', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Employees',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('eq_id', models.AutoField(primary_key=True, serialize=False)),
                ('invnum', models.CharField(blank=True, max_length=255, null=True)),
                ('eq_name', models.CharField(blank=True, max_length=255, null=True)),
                ('eq_type', models.CharField(blank=True, max_length=255, null=True)),
                ('area', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'Equipment',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Queries',
            fields=[
                ('query_id', models.AutoField(primary_key=True, serialize=False)),
                ('query_name', models.CharField(blank=True, max_length=45, null=True)),
                ('eq_id', models.IntegerField(blank=True, null=True)),
                ('post_time', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=45, null=True)),
                ('msg', models.TextField(blank=True, null=True)),
                ('eq_status', models.CharField(blank=True, max_length=45, null=True)),
                ('query_status', models.CharField(blank=True, max_length=45, null=True)),
                ('employee_id', models.IntegerField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Queries',
                'managed': True,
            },
        ),
    ]
