# Generated by Django 3.0.4 on 2020-04-03 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='comment',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
