# Generated by Django 3.0.4 on 2020-04-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_queries_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='comment',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
    ]
