# Generated by Django 3.0.4 on 2020-04-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200403_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queries',
            name='eq_status',
        ),
        migrations.AddField(
            model_name='equipment',
            name='eq_status',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
