# Generated by Django 3.0.4 on 2020-04-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200404_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='eq_status',
            field=models.CharField(choices=[('working', 'Работает'), ('stopped', 'Остановилось')], default='working', max_length=45),
        ),
    ]
