# Generated by Django 3.0.4 on 2020-04-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200404_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='eq_status',
            field=models.CharField(blank=True, choices=[('working', 'Работает'), ('stopped', 'Остановилось')], default='working', max_length=45, null=True),
        ),
    ]
