# Generated by Django 3.0.4 on 2020-04-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200404_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='eq_comment',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='area',
            field=models.CharField(blank=True, choices=[('Механической обработки', 'Механической обработки'), ('Слесарный', 'Слесарный'), ('Сварочный', 'Сварочный'), ('Сборки', 'Сборки'), ('Радиомонтажа', 'Радиомонтажа')], default='Сборки', max_length=45, null=True),
        ),
    ]
