# Generated by Django 3.0.4 on 2020-04-08 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200408_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 8, 22, 26, 27, 349193)),
        ),
        migrations.AlterModelTable(
            name='maintenance',
            table='maintenance',
        ),
    ]
