# Generated by Django 3.0.4 on 2020-04-09 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20200409_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='master',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 12, 57, 17, 241006)),
        ),
    ]
