# Generated by Django 3.0.4 on 2020-04-09 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200409_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queries',
            name='big_delta',
        ),
        migrations.RemoveField(
            model_name='queries',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='queries',
            name='restart_time',
        ),
        migrations.RemoveField(
            model_name='queries',
            name='small_delta',
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 9, 21, 51, 2, 801027)),
        ),
    ]
