# Generated by Django 3.0.4 on 2020-04-11 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20200409_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 12, 52, 53, 534107)),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='area',
            field=models.CharField(blank=True, choices=[('Механической обработки', 'Механической обработки'), ('Слесарный', 'Слесарный'), ('Сварочный', 'Сварочный'), ('Сборки', 'Сборки'), ('Радиомонтажа', 'Радиомонтажа')], max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='eq_status',
            field=models.CharField(blank=True, choices=[('working', 'Работает'), ('stopped', 'Остановилось')], max_length=45, null=True),
        ),
    ]
