# Generated by Django 3.0.4 on 2020-04-11 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20200411_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 11, 12, 54, 4, 630828)),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='eq_status',
            field=models.CharField(blank=True, choices=[('working', 'Работает'), ('stopped', 'Остановилось')], default='Работает', max_length=45, null=True),
        ),
    ]
