# Generated by Django 3.0.4 on 2020-04-17 21:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200416_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='worktime',
            name='month_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 0, 11, 1, 525222)),
        ),
    ]
