# Generated by Django 3.0.4 on 2020-04-18 16:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200418_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='shift',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 18, 19, 0, 33, 660591)),
        ),
    ]
