# Generated by Django 3.0.4 on 2020-04-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200418_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='eq_stoptime',
            name='shift_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eq_stoptime',
            name='shift_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
