# Generated by Django 3.0.4 on 2020-04-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_queries_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='test_emp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
