# Generated by Django 3.0.4 on 2020-04-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_queries_test_emp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='test_emp',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
