# Generated by Django 3.0.4 on 2020-04-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20200424_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='test_emp',
            field=models.TextField(blank=True, null=True),
        ),
    ]
