# Generated by Django 3.0.4 on 2020-04-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20200424_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queries',
            name='test_emp',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
