# Generated by Django 3.0.4 on 2020-04-28 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20200424_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='queries',
            old_name='test_emp',
            new_name='json_emp',
        ),
    ]
