# Generated by Django 3.0.4 on 2020-04-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20200428_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='multiple',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
