# Generated by Django 3.0.4 on 2020-05-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_worktime_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
