# Generated by Django 3.0.4 on 2020-05-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_reasons'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reasons',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='reasons',
            table='reasons',
        ),
    ]
