# Generated by Django 3.0.4 on 2020-05-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20200522_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reasons',
            name='reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
