# Generated by Django 3.0.4 on 2020-07-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20200522_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='eq_stoptime',
            name='now',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
