# Generated by Django 3.0.4 on 2020-07-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_eq_stoptime_now'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.IntegerField(blank=True, null=True)),
                ('eq_id', models.IntegerField(blank=True, null=True)),
                ('supply', models.TextField(blank=True, null=True)),
                ('emp_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'supplies',
                'managed': True,
            },
        ),
    ]
