# Generated by Django 3.0.4 on 2020-07-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_supplies'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='month_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='shift_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='shift_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
