# Generated by Django 3.0.4 on 2020-07-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_auto_20200721_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='expected_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
