# Generated by Django 3.0.4 on 2020-07-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_equipment_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_a_start', models.DateTimeField(blank=True, null=True)),
                ('kpi_a_end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dates',
                'managed': True,
            },
        ),
    ]
