# Generated by Django 3.0.4 on 2020-07-30 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='dates',
            name='chart',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
