# Generated by Django 3.0.4 on 2020-08-11 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0051_dates_chart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unstated_works',
            fields=[
                ('work_id', models.AutoField(primary_key=True, serialize=False)),
                ('what', models.CharField(blank=True, max_length=400, null=True)),
                ('post_time', models.DateTimeField(blank=True, null=True)),
                ('query_status', models.CharField(blank=True, max_length=45, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=3000, null=True)),
                ('json_emp', models.CharField(blank=True, max_length=45, null=True)),
                ('multiple', models.IntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'unstated_works',
                'managed': True,
            },
        ),
    ]
