# Generated by Django 3.0.4 on 2020-08-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_supplies_work_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField()),
                ('task', models.CharField(blank=True, max_length=3000, null=True)),
            ],
            options={
                'db_table': 'daily_tasks',
                'managed': True,
            },
        ),
    ]
