# Generated by Django 3.0.4 on 2020-08-13 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_auto_20200813_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_tasks',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
