# Generated by Django 3.0.4 on 2020-08-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_auto_20200813_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplies',
            name='to_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
