# Generated by Django 3.0.4 on 2020-08-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_supplies_to_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='photo_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
