# Generated by Django 3.0.4 on 2020-08-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_queries_photo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='plan_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
