# Generated by Django 3.0.4 on 2020-08-27 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_maintenance_plan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='status2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
