# Generated by Django 3.0.4 on 2020-09-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_maintenance_status2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
