# Generated by Django 3.0.4 on 2020-09-26 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_maintenance_plan2_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
