# Generated by Django 3.0.4 on 2020-11-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_queries_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='type',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
